import type { MemorizationItem, ReviewRating } from './spacedRepetition';
import { calculateReviewInterval, SCHEDULERS, type AlgorithmType } from './reviewAlgorithms';
import { DateTime } from 'luxon';

export const ALGORITHMS = Object.keys(SCHEDULERS) as AlgorithmType[];
export interface SimulationEvent { date: string; rating: ReviewRating }
export interface SimulationRow { event: SimulationEvent; before: MemorizationItem; after: MemorizationItem }
export function mockPassage(start: string, beginner: boolean): MemorizationItem {
  return { id: 'simulation-only', surah: 1, ayahStart: 1, ayahEnd: 7, interval: 1,
    nextReview: start, createdAt: start, easeFactor: 2.5, reviewCount: 0,
    isBeginner: beginner, beginnerStartedAtReview: 0 };
}
export function simulate(algorithm: AlgorithmType, start: string, beginner: boolean, events: SimulationEvent[], zone: string): SimulationRow[] {
  let item = mockPassage(start, beginner);
  return events.map(event => {
    const before = item;
    item = calculateReviewInterval(before, event.rating, { algorithm }, zone, event.date);
    return { event, before, after: item };
  });
}
const repeated = (rating: ReviewRating, count = 12) => Array<ReviewRating>(count).fill(rating);
export const PRESETS: Record<string, { ratings: ReviewRating[]; timing?: 'same-day' | 'overdue'; beginner?: boolean }> = {
  'Perfect recall': { ratings: repeated('easy') },
  'Consistent recall': { ratings: repeated('medium') },
  'Struggling': { ratings: repeated('hard') },
  'Mixed performance': { ratings: ['easy', 'easy', 'medium', 'hard', 'easy', 'medium', 'easy', 'easy'] },
  'Learned then forgotten': { ratings: [...repeated('easy', 6), 'hard'] },
  'Recovery': { ratings: ['hard', 'hard', 'medium', 'medium', 'easy', 'easy', 'easy'] },
  'Same-day repetition': { ratings: repeated('easy', 8), timing: 'same-day' },
  'Long overdue': { ratings: ['easy', 'medium', 'hard', 'easy'], timing: 'overdue' },
  'Beginner progression': { ratings: repeated('medium'), beginner: true },
};
/** Dates are generated by one selected reference scheduler, then shared by all algorithms. */
export function presetEvents(name: string, reference: AlgorithmType, start: string, beginner: boolean, zone: string): SimulationEvent[] {
  const preset = PRESETS[name];
  let item = mockPassage(start, beginner);
  let date = start;
  return preset.ratings.map((rating, index) => {
    if (index && preset.timing !== 'same-day') date = DateTime.fromISO(item.nextReview, { zone }).plus({ days: preset.timing === 'overdue' ? 90 : 0 }).toISODate()!;
    const event = { date, rating };
    item = calculateReviewInterval(item, rating, { algorithm: reference }, zone, date);
    return event;
  });
}
/** Each scheduler follows its own due dates. Prescribed ratings are NOT a memory/retention model. */
export function reviewBurden(algorithm: AlgorithmType, start: string, beginner: boolean, ratings: ReviewRating[], horizon: number, zone: string): number {
  let item = mockPassage(start, beginner);
  const end = DateTime.fromISO(start, { zone }).plus({ days: horizon }).toISODate()!;
  let count = 0;
  while (item.nextReview < end && count < horizon + 1) {
    item = calculateReviewInterval(item, ratings[count % ratings.length] ?? 'medium', { algorithm }, zone, item.nextReview);
    count++;
  }
  return count;
}
