export type Kind = 'note' | 'image' | 'link' | 'audio' | 'video' | 'file' | 'code' | 'stack';
export type Item = { id: string; kind: Kind; title: string; body?: string; url?: string; fileKey?: string; mime?: string; size?: number; island: string; pinned?: boolean; deleted?: boolean; created: number; x?: number; y?: number; stack?: string; tags?: string[] };
export type Workspace = {items: Item[]; islands: string[]; theme: string; accent: string; clipboard: Item[]; history: boolean; reduced: boolean};
const now = Date.now();
export const initial: Workspace = { islands: ['Personal space', 'Studio projects', 'Life & little things'], theme: 'light', accent: '#728369', history: true, reduced: false, clipboard: [], items: [
{id:'welcome-note', kind:'note', title:'A little room to think.',body:'Collect what inspires you.\nConnect the unexpected.\nMake something wonderful.\n\nNo perfect system required.', island:'Personal space', pinned:true, created:now, tags:['thoughts']},
{id:'coast',kind:'image',title:'Somewhere, slower.',url:'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1000&q=85',body:'A little perspective for the moodboard.',island:'Personal space',created:now-1000,tags:['inspiration']},
{id:'design-link',kind:'link',title:'Less, but better.',body:'Thoughts on designing with intention.',url:'https://www.vitsoe.com/us/about/good-design',island:'Personal space',created:now-2000,tags:['design']},
{id:'research',kind:'stack',title:'Creative direction',body:'A few things worth coming back to.',island:'Personal space',created:now-3000},
{id:'research-note',kind:'note',title:'The feeling comes first',body:'Quiet confidence. Natural materials. A balance of structure and softness.\n\nDesign for the moments between tasks.',island:'Personal space',stack:'research',created:now-3100},
{id:'research-link',kind:'link',title:'The creative independent',url:'https://thecreativeindependent.com',body:'A growing resource of emotional and practical guidance for creative people.',island:'Personal space',stack:'research',created:now-3200},
{id:'research-code',kind:'code',title:'A slower rhythm',body:'const makeRoom = () => {\n  return {\n    less: "noise",\n    more: "possibility"\n  };\n};',island:'Personal space',stack:'research',created:now-3300},
{id:'week-note',kind:'note',title:'This week, intentionally.',body:'☑ Make space for a new idea\n☐ Finish the studio moodboard\n☐ Read something unexpected\n☐ Take the scenic route',island:'Personal space',created:now-4000,tags:['this week']},
{id:'architecture',kind:'image',title:'Light, texture, stillness.',url:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85',island:'Personal space',created:now-5000,tags:['spaces']},
{id:'manifesto',kind:'code',title:'A small reminder.js',body:'const goodDay = {\n  focus: "one thing at a time",\n  space: "for the unexpected",\n  progress: true\n};',island:'Personal space',created:now-6000}
]};
function db(): Promise<IDBDatabase> {return new Promise((resolve,reject)=>{const request=indexedDB.open('dynamis-island',1);request.onupgradeneeded=()=>{request.result.createObjectStore('workspace'); request.result.createObjectStore('files');};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function readWorkspace(): Promise<Workspace | undefined> {const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction('workspace');const r=t.objectStore('workspace').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);t.oncomplete=()=>d.close();});}
export async function saveWorkspace(value: Workspace) {const d=await db();return new Promise<void>((resolve,reject)=>{const t=d.transaction('workspace','readwrite');t.objectStore('workspace').put(value,'current');t.oncomplete=()=>{d.close();resolve();};t.onerror=()=>{d.close();reject(t.error);};});}
export async function saveFile(key: string, file: Blob) {const d=await db();return new Promise<void>((resolve,reject)=>{const t=d.transaction('files','readwrite');t.objectStore('files').put(file,key);t.oncomplete=()=>{d.close();resolve();};t.onerror=()=>reject(t.error);});}
export async function readFile(key: string): Promise<Blob | undefined> {const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction('files');const r=t.objectStore('files').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);t.oncomplete=()=>d.close();});}
